### ISSUE TITLE
Respostas dos Exercícios

### ISSUE THREAD

**Issue by gafanhotos** [cursoemvideo/cursoemvideo-algoritmos#1]
### Teste1

Testando Issues **AGORA** e _DEPOIS_

> Testando 123

`teste`

op001 | op002
---|---
teste|teste

``` 
if lalala:
    opopop
    oiiiid
 ```

**Comment by gustavoguanabara** [comment]
Maravilha! Adorei!

**Comment by gustavoguanabara** [comment]
> ### Teste1
> Testando Issues **AGORA** e _DEPOIS_
> 
> > Testando 123
> 
> `teste`
> 
> op001	op002
> teste	teste
> ```
> if lalala:
>     opopop
>     oiiiid
> ```

Melhor postagem
