### ISSUE TITLE
Testando nova Issue

### ISSUE THREAD

**Issue by gafanhotos** [cursoemvideo/cursoemvideo-algoritmos#3]
Opa

**Comment by gustavoguanabara** [comment]
Já respondi isso em #1

**Comment by gustavoguanabara** [comment]
slkfjdsflkjsfklsd

![Gustavo Guanabara](https://user-images.githubusercontent.com/8683378/78829889-82e44800-79bd-11ea-8c43-c01dec380edf.png)
* Coisas grátis no [GitHub](https://gustavoguanabara.github.io) 
* Segue lá no [Instagram](https://www.instagram.com/gustavoguanabara/)
* Se inscreve lá no [YouTube](https://www.youtube.com/cursoemvideo)
